#!/bin/sh

os=$(cat "$__global/explorer/os")

case "$os" in
	debian|ubuntu)
		# Install netbox dependencies.
		for pkg in python3-pip python3-venv python3-dev build-essential libxml2-dev \
			libxslt1-dev libffi-dev libpq-dev libssl-dev zlib1g-dev curl virtualenv; do
			__package $pkg
		done

		if [ -f "$__object/parameter/ldap-server" ]; then
			for pkg in libldap2-dev libsasl2-dev libssl-dev; do
				__package $pkg
			done
		fi
		;;
	*)
		printf "Your operating system (%s) is currently not supported by this type (%s)\n" "$os" "${__type##*/}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac


DATABASE_NAME=$(cat "$__object/parameter/database")
export DATABASE_NAME
DATABASE_PASSWORD=$(cat "$__object/parameter/database-password")
export DATABASE_PASSWORD
ALLOWED_HOST=$(cat "$__object/parameter/host")
export ALLOWED_HOST
SECRET_KEY=$(cat "$__object/parameter/secret-key")
export SECRET_KEY

if [ -f "$__object/parameter/ldap-server" ]; then
	LDAP_SERVER=$(cat "$__object/parameter/ldap-server")
	export LDAP_SERVER
fi

if [ -f "$__object/parameter/ldap-bind-dn" ]; then
	LDAP_BIND_DN=$(cat "$__object/parameter/ldap-bind-dn")
	export LDAP_BIND_DN
fi

if [ -f "$__object/parameter/ldap-bind-password" ]; then
	LDAP_BIND_PASSWORD=$(cat "$__object/parameter/ldap-bind-password")
	export LDAP_BIND_PASSWORD
fi

if [ -f "$__object/parameter/ldap-user-base" ]; then
	LDAP_USER_BASE=$(cat "$__object/parameter/ldap-user-base")
	export LDAP_USER_BASE
fi

if [ -f "$__object/parameter/ldap-group-base" ]; then
	LDAP_GROUP_BASE=$(cat "$__object/parameter/ldap-group-base")
	export LDAP_GROUP_BASE
fi

if [ -f "$__object/parameter/ldap-require-group" ]; then
	LDAP_REQUIRE_GROUP=$(cat "$__object/parameter/ldap-require-group")
	export LDAP_REQUIRE_GROUP
fi

if [ -f "$__object/parameter/ldap-superuser-group" ]; then
	LDAP_SUPERUSER_GROUP=$(cat "$__object/parameter/ldap-superuser-group")
	export LDAP_SUPERUSER_GROUP
fi

# have default values
REDIS_HOST="$(cat "$__object/parameter/redis-host")"
export REDIS_HOST
REDIS_PORT="$(cat "$__object/parameter/redis-port")"
export REDIS_PORT
REDIS_PASSWORD="$(cat "$__object/parameter/redis-password")"
export REDIS_PASSWORD
REDIS_DBID_OFFSET="$(cat "$__object/parameter/redis-dbid-offset")"
export REDIS_DBID_OFFSET
if [ -f "$__object/parameter/redis-ssl" ]; then
    REDIS_SSL="True"
else
    REDIS_SSL="False"
fi
export REDIS_SSL

SMTP_HOST="$(cat "$__object/parameter/smtp-host")"
export SMTP_HOST
SMTP_PORT="$(cat "$__object/parameter/smtp-port")"
export SMTP_PORT
SMTP_USER="$(cat "$__object/parameter/smtp-user")"
export SMTP_USER
SMTP_PASSWORD="$(cat "$__object/parameter/smtp-password")"
export SMTP_PASSWORD
SMTP_FROM_EMAIL="$(cat "$__object/parameter/smtp-from-email")"
export SMTP_FROM_EMAIL

if [ -f "$__object/parameter/smtp-use-ssl" ]; then
    SMTP_USE_SSL="True"
else
    SMTP_USE_SSL="False"
fi
export SMTP_USE_SSL
if [ -f "$__object/parameter/smtp-use-tls" ]; then
    if [ "$SMTP_USE_SSL" = "True" ]; then
        echo "options --smtp-use-ssl and --smtp-use-tls are not compatible"
        exit 2
    fi
    SMTP_USE_TLS="True"
else
    SMTP_USE_TLS="False"
fi
export SMTP_USE_TLS

BASEPATH="$(cat "$__object/parameter/basepath")"
export BASEPATH

if [ -f "$__object/parameter/http-proxy" ]; then
	HTTP_PROXY=$(cat "$__object/parameter/http-proxy")
	export HTTP_PROXY
fi
if [ -f "$__object/parameter/https-proxy" ]; then
	HTTPS_PROXY=$(cat "$__object/parameter/https-proxy")
	export HTTPS_PROXY
fi

if [ -f "$__object/parameter/login-required" ]; then
    LOGIN_REQUIRED="True"
else
    LOGIN_REQUIRED="False"
fi
export LOGIN_REQUIRED


# Create system user used to run netbox.
__user netbox --system --home /opt/netbox --create-home

# Generate and upload netbox configuration.
mkdir -p "$__object/files"
"$__type/files/configuration.py.sh" > "$__object/files/configuration.py"
"$__type/files/ldap_config.py.sh" > "$__object/files/ldap_config.py"

require="__user/netbox" __directory /opt/netbox/netbox/cdist --parents
require="__directory/opt/netbox/netbox/cdist " __file \
	/opt/netbox/netbox/cdist/configuration.py --mode 640 --owner netbox \
	--source "$__object/files/configuration.py"

if [ -f "$__object/parameter/ldap-server" ]; then
	require="__directory/opt/netbox/netbox/cdist " __file \
		/opt/netbox/netbox/cdist/ldap_config.py --mode 640 --owner netbox \
		--source "$__object/files/ldap_config.py"
fi


# Upload systemd units and gunicorn configuration.
for unit in netbox netbox-rq; do
	__systemd_unit $unit.service \
		--source "$__type/files/$unit.service" \
		--enablement-state enabled
done

# Python worker configuration.
require="__user/netbox" __file /opt/netbox/gunicorn.py \
	--mode 644 --source "$__type/files/gunicorn.py"
