#!/bin/sh -e

if [ ! -f "$__object/require" ]
then
    echo '$require not set' >&2
    exit 1
fi

__check()
{
    if [ -s "$__messages_out" ]
    then
        return
    fi

    object="$1"
    object_path="$__global/object/$object"

    for check_file in code-local code-remote children
    do
        check_file_path="$object_path/$__cdist_object_marker/$check_file"

        if [ ! -s "$check_file_path" ]
        then
            continue
        fi

        case "$check_file" in
            code-*)
                echo "$object/$check_file" >> "$__messages_out"
                break
            ;;
            children)
                __objects "$check_file_path"
            ;;
        esac
    done
}

__objects()
{
    while read -r object
    do __check "$object"
    done < "$1"
}

__objects "$__object/require"

if [ -s "$__messages_out" ]
then
    cat "$__object/parameter/onchange"
fi
