#!/bin/sh -e
#
# 2025 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

if [ ! -f "${__object:?}/require" ]
then
    echo '${require} not set' >&2
    exit 1
fi

__check()
{
    if [ -s "${__messages_out:?}" ]
    then
        return
    fi

    object=$1
    object_path="${__global:?}/object/${object}"

    for check_file in code-local code-remote children
    do
        check_file_path="${object_path}/${__cdist_object_marker:?}/${check_file}"

        if [ ! -s "${check_file_path}" ]
        then
            continue
        fi

        case "${check_file}" in
            code-*)
                echo "${object}/${check_file}" >> "${__messages_out:?}"
                break
            ;;
            children)
                __objects "${check_file_path}"
            ;;
        esac
    done
}

__objects()
{
    while read -r object
    do __check "${object}"
    done < "$1"
}

__objects "${__object:?}/require"

if [ -s "${__messages_out:?}" ]
then
    cat "${__object:?}/parameter/onchange"
fi
