#!/bin/sh -e

# control state
state="$(cat "$__object/parameter/state")"

case "$state" in
    # install uwsgi
    enabled|disabled)
        # not installed
        if ! [ -s "$__object/explorer/installed" ]; then
            echo "/opt/netbox/venv/bin/pip3 install uwsgi"
            do_restart=yes
            printf "installed\n" >> "$__messages_out"

        # updates available
        elif [ -s "$__object/explorer/upgradeable" ]; then
            echo "/opt/netbox/venv/bin/pip3 install --upgrade uwsgi"
            do_restart=yes
            printf "upgraded\n" >> "$__messages_out"
        fi

        # changed configuration
        if grep -q "^__file/opt/netbox/uwsgi.ini:" "$__messages_in"; then
            do_restart=yes
            printf "configured\n" >> "$__messages_out"
        fi


        # restart uwsgi
        if [ "$do_restart" ] && [ "$state" != "disabled" ]; then
            cat << EOF
# Restart service
systemctl restart uwsgi-netbox
EOF
        fi
        ;;

    # uninstall
    absent)
        # check if installed
        if [ -s "$__object/explorer/installed" ]; then
            # service already disabled
            echo "/opt/netbox/venv/bin/pip3 uninstall -y uwsgi"
            printf "uninstalled\n" >> "$__messages_out"
        fi
        ;;
esac
