#!/bin/sh -e
#
# 2022 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the system packages which are required to be installed for this opam
# package to be installed.
#

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }

command -v opam >/dev/null 2>&1 || {
	# cannot determine depexts
	echo '?'
	exit 0
}

opam_vars='OPAMUTF8=never OPAMCOLOR=never OPAMROOTISOK=1 OPAMSTATUSLINE=never OPAMCLI=2.0'
if test -s "${__object:?}/parameter/root"
then
	OPAMROOT=$(cat "${__object:?}/parameter/root")
	opam_vars="${opam_vars} OPAMROOT=$(quote "${OPAMROOT}")"
fi
if test -s "${__object:?}/parameter/switch"
then
	read -r OPAMSWITCH <"${__object:?}/parameter/switch"
	opam_vars="${opam_vars} OPAMSWITCH=$(quote "${OPAMSWITCH}")"
fi

read -r user <"${__object:?}/parameter/user"

su - "${user}" -c "${opam_vars} exec opam var --readonly os-family"
