#!/bin/sh -e
#
# 2022 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current state of the opam package.
#

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }

command -v opam >/dev/null 2>&1 || {
	# no opam -> no package
	echo 'absent'
	exit 0
}

opam_vars='OPAMUTF8=never OPAMCOLOR=never OPAMROOTISOK=1 OPAMSTATUSLINE=never OPAMCLI=2.0'
read -r OPAMSWITCH <"${__object:?}/parameter/switch"
opam_vars="${opam_vars} OPAMSWITCH=$(quote "${OPAMSWITCH}")"

read -r user <"${__object:?}/parameter/user"

if test -s "${__object:?}/parameter/package"
then
	read -r name <"${__object:?}/parameter/package"
else
	name=${__object_id:?}
fi

if
	su - "${user}" -c "${opam_vars} exec opam list --readonly --short --installed $(quote "${name}")" \
	| grep -qxF "${name}"
then
	echo 'present'
else
	echo 'absent'
fi
