#!/bin/sh -e

curr_installed="$(cat "$__object/explorer/installed")"
should_installed="$(cat "$__object/explorer/should_installed")"

# gunicorn version change
if [ "$curr_installed" != "$should_installed" ]; then
    # (re)installing gunicorn
    echo "/opt/netbox/venv/bin/pip3 install 'gunicorn==$should_installed'"

    do_restart=yes
    printf "updated %s to %s\n" "$curr_installed" "$should_installed" \
        >> "$__messages_out"
fi

# configuration changes
if grep -q "^__file/opt/netbox/gunicorn.py:" "$__messages_in"; then
    do_restart=yes
    printf "configured\n" >> "$__messages_out"
fi

# application
if grep -q "^__netbox:" "$__messages_in"; then
    do_restart=yes
    # no message cause it should be obvious
fi


# restart gunicorn
if [ "$do_restart" ]; then
    cat << EOF
# Restart service
service gunicorn-netbox restart
EOF
fi
