#!/bin/sh -e
#
# 2020 Matthias Stecher (matthiasstecher at gmx.de)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

# control state
state=$(cat "${__object:?}/parameter/state")

case "${state}" in
    # install gunicorn
    enabled|disabled)
        curr_installed=$(cat "${__object:?}/explorer/installed")
        should_installed=$(cat "${__object:?}/explorer/should_installed")

        # gunicorn version change
        if [ "${curr_installed}" != "${should_installed}" ]; then
            # (re)installing gunicorn
            echo "/opt/netbox/venv/bin/pip3 install 'gunicorn==${should_installed}'"

            if [ "${curr_installed}" != "" ]; then
                printf "updated %s to %s\n" "${curr_installed}" "${should_installed}" \
                    >> "${__messages_out:?}"
            else
                printf "installed\n" >> "${__messages_out:?}"
            fi
            do_restart=yes
        fi

        # configuration changes
        if grep -q "^__file/opt/netbox/gunicorn.py:" "${__messages_in:?}"; then
            do_restart=yes
            printf "configured\n" >> "${__messages_out:?}"
        fi


        # restart gunicorn
        if [ "${do_restart}" ] && [ "${state}" != "disabled" ]; then
            cat << EOF
# Restart service
systemctl restart gunicorn-netbox
EOF
        fi
        ;;

    # uninstall
    absent)
        # check if installed
        if [ -s "${__object:?}/explorer/installed" ]; then
            # service already disabled
            echo "/opt/netbox/venv/bin/pip3 uninstall -y gunicorn"
            printf "uninstalled\n" >> "${__messages_out:?}"
        fi
esac
