#!/bin/sh -e
#
# 2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "${__global:?}/explorer/os")

case "$os" in
	'alpine'|'debian'|'ubuntu')
		confdir=/etc/bird.d
	;;
	*)
		printf "Your operating system (%s) is currently not supported by __bird_static\n" "$os" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
	;;
esac

# Required parameter route is directly accessed in template.
# Boolean  parameter ipv4  is directly accessed in template.
# Optional parameter description
description=
if [ -f "${__object:?}/parameter/description" ];
then
	description=$(cat "${__object:?}/parameter/description")
fi
export description

# Run template
"${__type:?}"/files/template.sh > "${__files:?}/static-${__object_id:?}.conf"

# Install resulting configuration
__file "${confdir:?}"/static-"${__object_id:?}".conf \
	--mode 0640 --owner root --group bird \
	--source "${__files:?}/static-${__object_id:?}.conf"
