#!/bin/sh -e
#
# 2017 Kamila Součková (kamila at ksp.sk)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

package=${__object_id:?}

cat<<EOF
[ -f /etc/environment ] && . /etc/environment
[ -f /etc/profile     ] && . /etc/profile
export GOPATH=\${GOPATH:-/opt/gocode}
go get ${package}
EOF
