#!/bin/sh -e
#
# 2017 Kamila Součková (kamila at ksp.sk)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

go_executable=$(cat "${__object:?}/explorer/go-executable")
[ -z "${go_executable}" ] && echo "__go_get: Cannot find go executable; make sure it is installed and in PATH" >&2 && exit 1

os=$(cat "${__global:?}/explorer/os")
case ${os}
in
	(debian|devuan|ubuntu)
		__package build-essential
		;;
	(*)
		echo "__go_get: Don't know how to install g++ on ${os}" >&2
		echo "__go_get: Send a pull request or contact <kamila@ksp.sk> to add support for ${os}." >&2
		exit 1
		;;
esac

__package git
