#!/bin/sh -e
#
# 2022 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }

read -r state_should <"${__object:?}/parameter/state"
state_is=$("${__type:?}/files/state_is.sh")

test "${state_should}" != "${state_is}" || exit 0

read -r user <"${__object:?}/parameter/user"
if test -s "${__object:?}/parameter/name"
then
	read -r name <"${__object:?}/parameter/name"
else
	name=${__object_id:?}
fi

opam_vars='OPAMROOTISOK=1 OPAMCOLOR=never OPAMUTF8=never OPAMSTATUSLINE=never OPAMCLI=2.0'

OPAMROOT=$(cat "${__object:?}/explorer/root-dir")
opam_vars="${opam_vars} OPAMROOT=$(quote "${OPAMROOT}")"

opam_cmd() {
	printf 'su - %s -c %s%s\n' \
		"${user}" \
		"$(quote "${opam_vars-}${opam_vars:+ }exec opam $1")" \
		"${2-}"
}

case ${state_should}
in
	(present)
		case ${state_is}
		in
			(absent)
				create_cmd="switch --no-switch --no-install create $(quote "${name}")"

				# create the switch
				if test -f "${__object:?}/parameter/empty"
				then
					create_cmd="${create_cmd} --empty"
				elif test -s "${__object:?}/parameter/compiler"
				then
					read -r compiler <"${__object:?}/parameter/compiler"
					create_cmd="${create_cmd} $(quote "${compiler}")"
				fi

				if test -f "${__object:?}/parameter/description"
				then
					description=$(cat "${__object:?}/parameter/description")
					create_cmd="${create_cmd} --description=$(quote "${description}")"
				fi

				opam_cmd "${create_cmd}"
				;;
			(different)
				# check what we need to modify

				# description?
				if test -f "${__object:?}/parameter/description" \
					&& ! {
						sed -n -e 's/^description=//p' "${__object:?}/explorer/attributes" \
						| LC_ALL=C tr '\036' '\n' \
						| cmp -s "${__object:?}/parameter/description" -
					}
				then
					# shellcheck disable=SC2016
					opam_vars="${opam_vars-} OPAMSWITCH=$(quote "${name}")" \
					opam_cmd \
						"switch set-description \"\$(cat)\"" \
						' <"${__object:?}/parameter/description"'
				fi

				# compiler?
				# TODO
				;;
			(*)
				printf 'Incomprehensible state_is: %s\n' "${state_is}" >&2
				exit 1
				;;
		esac
		;;
	(absent)
		# delete the switch
		# shellcheck disable=SC2016
		printf 'switch_dir=$(%s)\n' "$(opam_cmd "var --switch $(quote "${name}") prefix")"
		opam_cmd "switch remove $(quote "${name}") --yes"
		# shellcheck disable=SC2016
		printf 'if test -d "${switch_dir}"; then rm -R -f "${switch_dir}"; fi\n'
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
