#!/bin/sh -e
#
# 2020 Matthias Stecher (matthiasstecher at gmx.de)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Outputs the current state of the app. There are:
#  - `enabled` if the app is enabled
#  - `disabled` if the app is disabled
#  - `absent` if the app does not exist
#  - nothing if nextcloud is not installed
#

# Get the app id
appid="$__object/parameter/appid"
if [ -f "$appid" ]; then
    appid="$(cat "$appid")"
else
    appid="$__object_id"
fi

# Get the installation directory
cloud="$(cat "$__object/parameter/cloud")"
www_user="$(cat "$__object/parameter/www-user")"


# Check if the installation directory exists
if [ -d "$cloud" ]; then
    # if those files exist, everything should be fine
    if [ -f "$cloud/occ" ] && [ -f "$cloud/config/config.php" ]; then
        # Check if the app exists in the correct user context
        su -s /bin/sh -l "$www_user" -- -e <<SU
cd '$cloud'

# Output all apps and search in which category it is
php occ --no-warnings --no-interaction --no-ansi --output=plain app:list \
    | awk '\$0 == "Enabled:"{state="enabled"} \$0 == "Disabled:"{state="disabled"}
           /^  - ${appid}:?/{found=1; print state; exit} END{if(!found) print "absent"}'
SU
    fi
fi
