#!/bin/sh -e
#
# 2017 Kamila Součková (kamila at ksp.sk)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

RUN_PREFIX="#!/bin/sh
exec 2>&1
exec "  # mind the space :D

name=$__object_id
servicedir=$(cat "$__object/parameter/servicedir")
run=$(cat "$__object/parameter/run")
runfile=$(cat "$__object/parameter/run-file")
logrun=$(cat "$__object/parameter/log-run")

svc=$(cat "$__type/explorer/svc")

if [ -z "$svc" ]; then
	echo "svc not found! Install daemontools first: see __daemontools"
	exit 1
fi

badusage() {
	echo "__daemontools_service/$__object_id: exactly one of --run, --run-file must be set" >&2
	exit 1
}

[ -z "$run$runfile" ] && badusage
[ -n "$run" ] && [ -n "$runfile" ] && badusage

__directory "$servicedir/$name/log/main" --parents

echo "$RUN_PREFIX$run" | require="__directory/$servicedir/$name/log/main" __config_file "$servicedir/$name/run" \
	--onchange "svc -t '$servicedir/$name' 2>/dev/null" \
	--mode 755 \
	--source "${runfile:--}"

echo "$RUN_PREFIX$logrun" | require="__directory/$servicedir/$name/log/main" __config_file "$servicedir/$name/log/run" \
	--onchange "svc -t '$servicedir/$name/log' 2>/dev/null" \
	--mode 755 \
	--source "-"
