#!/bin/sh
#
# 2017 Kamila Součková (kamila at ksp.sk)
# 2019 Ahmed Bilal Khalid (ahmedbilal96 at gmail.com)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

export GOBIN=/opt/gocode/bin  # where to find go binaries

exporter=$(cat "$__object/parameter/exporter")
[ -z "$exporter" ] && exporter="$__object_id"

__user prometheus
require="__user/prometheus" __group prometheus
require="__group/prometheus" __user_groups prometheus --group prometheus

require="__user_groups/prometheus"
case $exporter in
	node)
		TEXTFILES=/service/node-exporter/textfiles  # path for the textfiles collector
		__directory $TEXTFILES --parents --mode 777
		require="$require __golang_from_vendor" __go_get github.com/prometheus/node_exporter

		port=9100
		run="setuidgid prometheus $GOBIN/node_exporter -web.listen-address :$port -collector.textfile.directory=$TEXTFILES"
	;;
	blackbox)
		require="$require __daemontools_service/${exporter}-exporter __user/prometheus" __config_file "/service/${exporter}-exporter/blackbox.yml" \
			--source "$__type/files/blackbox.yml" \
			--group prometheus --mode 640 \
			--onchange "svc -h /service/${exporter}-exporter"
		require="$require __golang_from_vendor" __go_get github.com/prometheus/blackbox_exporter

		port=9115
		run="setuidgid prometheus $GOBIN/blackbox_exporter -config.file=/service/${exporter}-exporter/blackbox.yml"
	;;
	ceph)
		__package librados-dev  # dependency of ceph_exporter
		require="$require __golang_from_vendor __package/librados-dev" __go_get github.com/digitalocean/ceph_exporter

		port=9128
		run="setuidgid ceph $GOBIN/ceph_exporter -ceph.config /etc/ceph/ceph.conf -telemetry.addr :$port"
	;;
	*)
		echo "Unsupported exporter: $exporter." >&2
		exit 1
	;;
esac

require="$require __daemontools" __daemontools_service "${exporter}-exporter" --run "$run"
if [ -f "$__object/parameter/add-consul-service" ]; then
	__consul_service "${exporter}-exporter" --port "$port" --check-http "http://localhost:$port/metrics" --check-interval 10s
fi

#__daemontools --install-init-script
__daemontools
__golang_from_vendor --version 1.9  # required for many exporters
