#!/bin/sh -e
#
# 2017-2018 Kamila Součková (kamila at ksp.sk)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

pkg=$(cat "$__object/parameter/from-package")
servicedir=$(cat "$__object/parameter/servicedir")

__package "$pkg"
__directory "$servicedir" --mode 700

os=$(cat "$__global/explorer/os")
init=$(cat "$__global/explorer/init")

require=""
case $os in
	freebsd)
		# TODO change to __start_on_boot once it supports freebsd
		__config_file /etc/rc.conf.d/svscan --source - <<-EOT
			svscan_enable="YES"
			svscan_servicedir="$servicedir"
		EOT
		require="$require __package/$pkg __directory/$servicedir __config_file/etc/rc.conf.d/svscan" \
		__process svscan --name ".*/svscan $servicedir" --start 'service svscan start'
	;;
	*)
		case $init in
			init)
				if [ -f "$__object/parameter/install-init-script" ]; then
					__config_file /etc/init.d/svscan --mode 755 --source "$__type/files/init.d-svscan"
					REQUIREEXTRA="__config_file/etc/init.d/svscan"
				fi
				require="$require $REQUIREEXTRA" __start_on_boot svscan
				require="$require __package/$pkg __directory/$servicedir __start_on_boot/svscan" \
				__process svscan --name ".*/svscan $servicedir" --start 'service svscan start'
			;;
			*)
				echo "Your init system ($init) is not supported by this type. Submit a patch at github.com/ungleich/cdist!"
				exit 1
			;;
		esac
	;;
esac
