#!/bin/sh
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
# 2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

# FIXME: this code is duplicated from the manifest -> let's share it somehow.

os=$(cat "${__global:?}"/explorer/os)
case ${os}
in
	alpine|ubuntu|debian)
		default_confdir=/etc/ssl/uacme
	;;
	*)
		echo "__uacme_obtain currently has no implementation for ${os}. Aborting." >&2;
		exit 1;
	;;
esac

confdir="${default_confdir:?}"
if [ -f "${__object:?}/parameter/confdir" ];
then
	confdir=$(cat "${__object:?}/parameter/confdir")
fi

# Run renew script 'by hand' for intial issue - renews will be handled by the
# cronjob.
echo "${confdir}/${__object_id:?}/renew.sh"
