#!/bin/sh -e
#
# 2025 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

is_present="${__object:?}/explorer/present"
should_present="${__object:?}/parameter/present"
should_absent="${__object:?}/parameter/absent"

for packages_list in "${should_present}" "${should_absent}"
do
    test ! -f "${packages_list}" && continue

    package_state=$(basename "${packages_list}")

    case "${package_state}"
    in
        (present)
            set -- '-23'
            ;;
        (absent)
            set -- '-12'
            ;;
    esac

    grep '^[^#]' "${packages_list}" \
    | LC_ALL=C sort \
    | comm "$@" - "${is_present}" \
    | while read -r package_name
    do
        __package "${package_name}" \
            --state "${package_state}" \
            </dev/null
    done
done
