#!/bin/sh -e
#
# 2022 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "${__global:?}/explorer/os")

case ${os}
in
	(openwrt)
		__package openssl --name openssl-util

		if test -f "${__object:?}/parameter/background" \
			&& ! cmp -s "${__object:?}/explorer/state" "${__object:?}/parameter/state"
		then
			# nohup is required for --background to work (but only install it
			# when a new file needs to be generated)
			__package_opkg coreutils-nohup --state present
		fi
		;;
	(*)
		__package openssl
		;;
esac
