#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

kernel_name=$(cat "${__global:?}/explorer/kernel_name")

if grep -q -e '^__block/etc/modprobe.d/zfs.conf:' "${__messages_in:?}" \
	&& test "${kernel_name}" = 'Linux'
then
	# tunables changed -> also update running config (currently only on Linux)
	cat <<-'EOF'
	sed -n -e 's/^options \(.*\)/\1/p' /etc/modprobe.d/zfs.conf \
	| while read -r kmod tunable
	  do
		  printf '%s\n' "${tunable#*=}" >"/sys/module/${kmod}/parameters/${tunable%%=*}"
	  done
	EOF
fi
