#!/bin/sh -e
#
# 2020 Timothée Floure (timothee.floure at ungleich.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "${__global:?}/explorer/os")

case ${os}
in
    alpine)
        # Used in gencode-remote.
        __package curl
        __package tar
        __package openssl
        __package go
        __package libc-dev
        ;;
    *)
        printf "Your operating system (%s) is currently not supported by this type (%s)\n" "${os}" "${__type##*/}" >&2
        printf "Please contribute an implementation for it if you can.\n" >&2
        exit 1
        ;;
esac

__file /etc/init.d/unbound_exporter \
    --source "${__type:?}/files/openrc-service" \
    --mode 755

require="__file/etc/init.d/unbound_exporter" __start_on_boot unbound_exporter
