#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "${__global:?}/explorer/os")

state_should=$(cat "${__object:?}/parameter/state")

case ${os}
in
	(debian|devuan|ubuntu)
		# NOTE: the explorer will only print packages if --state requires them.
		while read -r pkgname
		do
			__package "${pkgname}" </dev/null
			require=${require-}${require:+ }__package/${pkgname}
		done <"${__object:?}/explorer/packages-required"
		export require  # important!

		__start_on_boot uwsgi

		case ${state_should}
		in
			(present)
				need_config_file=true
				uwsgi_app_available_state=present
				uwsgi_app_enabled_state=present
				;;
			(disabled)
				need_config_file=true
				uwsgi_app_available_state=present
				uwsgi_app_enabled_state=absent
				;;
			(absent)
				need_config_file=false
				uwsgi_app_available_state=absent
				uwsgi_app_enabled_state=absent
				;;
		esac

		if ${need_config_file}
		then
			# generate config file
			mkdir "${__object:?}/files"
			"${__type:?}/files/gen-config-ini.sh" >"${__object:?}/files/${__object_id:?}.ini"
		fi

		test "${uwsgi_app_available_state}" != 'absent' || require="${require-}${require:+ }__link/etc/uwsgi/apps-enabled/${__object_id:?}.ini"
		__file "/etc/uwsgi/apps-available/${__object_id}.ini" \
			--state "${uwsgi_app_available_state}" \
			--owner 0 --group 0 --mode 0644 \
			--source "${__object:?}/files/${__object_id}.ini"

		test "${uwsgi_app_enabled_state}" = 'absent' || require="${require-}${require:+ }__file/etc/uwsgi/apps-available/${__object_id:?}.ini"
		__link "/etc/uwsgi/apps-enabled/${__object_id}.ini" \
			--state "${uwsgi_app_enabled_state}" \
			--type symbolic \
			--source "../apps-available/${__object_id}.ini"
		;;
	(*)
		: "${__type:?}"  # make shellcheck happy
		printf "Your operating system (%s) is currently not supported by this type (%s)\n" "${os}" "${__type##*/}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac
