#!/bin/sh
#
# 2020 Timothée Floure (timothee.floure at posteo.net)
# 2020 Mark Verboom (mark at verboom.net)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

manager=$(cat "${__object:?}/explorer/service-manager")

name=${__object_id:?}
action=$(cat "${__object:?}/parameter/action")

case ${manager}
in
	systemd)
		test "${action}" = "start" && action="running"
		test "${action}" = "stop"  && action="stopped"
		__systemd_service "${name}" --state "${action}"
	;;
	*)
		# Unknown: handled by `service ${NAME} ${action}` in gencode-remote.
	;;
esac
