#!/bin/sh -e
# Send mails using sendmail. Based on smartmontools Example7 script

if test -x /usr/bin/mail
then
	# already sent mail in 10mail
	exit 0
fi

if test $# -lt 3 -o "$1" != "-s"
then
	echo "Usage: $0 -s SUBJECT ADDRESS... < MESSAGE"
	exit 1
fi

command -v sendmail || {
	echo 'Your system does not have sendmail installed.' >&2
	exit 1
}

shift
SUBJECT=$1
shift


exec sendmail "$@" <<EOF
To: $(echo "$*" | sed 's/ /, /g')
Subject: ${SUBJECT}

$(cat)
EOF
