#!/bin/sh -e
#
# 2025 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Prints a sorted list of the packages currently installed.
#

os=$("${__explorer:?}/os")

case ${os} in
    (debian|ubuntu|devuan)
        dpkg-query -W -f '${Package}\n' | LC_ALL=C sort
        ;;
    (*)
        echo "${os} not supported" >&2
        exit 1
        ;;
esac
