#!/bin/sh -e
#
# 2020 Matthias Stecher (matthiasstecher at gmx.de)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Checks the nextcloud configuration
#

# Get the installdir
installdir="/$__object_id"

# Check if the tools are available
if [ -d "$installdir" ]; then
    cd "$installdir"

    # if those files exist, everything should be good
    if [ -f "occ" ] && [ -f "config/config.php" ]; then
        # Dump out config instead of fuzz every possible option through
        # `occ config:system:get`. Or parse through the whole json or
        # yaml-like output of `occ config:list system --private`.
        #
        # shellcheck disable=SC2016  # cause of the php inline code
        php -r 'require("lib/private/Config.php"); $config = new OC\Config("config/");
                function printv($key, $value) {printf("%s = %s\n", $key, $value);}
                foreach($config->getKeys() as $key){
                    $value = $config->getValue($key);
                    if(is_array($value)) foreach($value as $n => $in) printv($n."|".$key, $in);
                    else printv($key, $value);
                };'
    fi
fi
