#!/bin/sh -e
#
# 2020 Matthias Stecher (matthiasstecher at gmx.de)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Check the currently installed version. Outputs nothing if nothing found.
#

# Get the install directory
installdir="/${__object_id:?}"

# Check if the installation directory exists
if [ -d "${installdir}" ]
then
    cd "${installdir}"

    # if those files exist, everything should be good
    if [ -f "occ" ] && [ -f "version.php" ]
    then
        # Detect php version with the version file.
        # shellcheck disable=SC2016  # cause of the php inline code
        php -r 'require("version.php"); print($OC_VersionString);'
    fi
fi
