#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Print the packages that need to be installed for this uWSGI app to be
# functional (plugins only)

test -s "${__object:?}/parameter/plugin" || exit 0

os=$("${__explorer:?}/os")

case ${os}
in
	(debian|devuan|ubuntu)
		test "$(cat "${__object:?}/parameter/state")" != absent || exit 0

		while read -r pkgname
		do
			if apt-cache showpkg "${pkgname}" >/dev/null 2>&1
			then
				printf '%s\n' "${pkgname}"
			fi
		done <<-EOF
		$(sed 's/^/uwsgi-plugin-/' <"${__object:?}/parameter/plugin")
		EOF
		;;
	(*)
		;;
esac
