#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Print the packages that need to be installed for this uWSGI app to be
# functional (plugins only)

test -s "${__object:?}/parameter/plugin" || exit 0

os=$("${__explorer:?}/os")

case ${os}
in
	(debian|devuan|ubuntu)
		test "$(cat "${__object:?}/parameter/state")" != absent || exit 0

		pkg_exists() { apt-cache show "$1" >/dev/null 2>&1; }

		while read -r plugin
		do
			case ${plugin}
			in
				(rack)
					ruby_version=$(
						apt-cache show ruby \
						| awk -F': ' \
						  '$1 == "Depends" {
							  split($2, d, ", ")
							  for (i in d)
								  if (d[i] ~ /^ruby[0-9]/)
									  print d[i]
						  }')
					pkgname="uwsgi-plugin-${plugin}-${ruby_version}"
					;;
				(http)
					pkgname='uwsgi-core'
					;;
				(*)
					pkgname="uwsgi-plugin-${plugin}"
					;;
			esac
			if pkg_exists "${pkgname}"
			then
				printf '%s\n' "${pkgname}"
			fi
		done <"${__object:?}/parameter/plugin"
		;;
	(*)
		# TODO
		;;
esac
