#!/bin/sh -e
#
# 2020 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

# Check pass is installed.
command -v pass >/dev/null 2>&1 ||
	{
		cat <<- EOF >&2
		__pass_init: this type requires pass installed.
		See https://www.passwordstore.org/.
		EOF
		exit 1;
	}

# Load required GPG ID parameters.
set --
while read -r id;
do
	set -- "$@" "$id"
done < "${__object:?}/parameter/gpgid"

# Load required password store location parameter.
PASSWORD_STORE_DIR=$(cat "${__object:?}/parameter/storedir")
export PASSWORD_STORE_DIR

# Do our work.
pass init "$@" >/dev/null
