#!/bin/sh -e
#
# 2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")

case "${os}" in
'alpine')
	backend=busybox-openrc
	;;
'debian' | 'ubuntu')
	backend=systemd-timesyncd
	;;
*)
	printf "__networktime is not yet implemented for %s.\n" "${os}" >&2
	printf "Please contribute an implementation for it if you can.\n" >&2
	exit 1
	;;
esac

case "${backend}" in
'busybox-openrc')
	argstring="-N"
	while read -r peer;
	do
		argstring="${argstring} -p ${peer}"
	done < "${__object:?}/parameter/peer"

	__start_on_boot ntpd

	__file /etc/conf.d/ntpd \
		--mode 0644 --onchange "service ntpd restart"\
		--source - <<- EOF
		# NTPd OpenRC configuration file. Managed by cdist.
		NTPD_OPTS=${argstring}
		EOF
	;;

'systemd-timesyncd')
	peers=$(tr '\n' ' ' < "${__object:?}/parameter/peer")

	__package ntp --state absent
	require="__package/ntp" __systemd_unit systemd-timesyncd \
		--enablement-state enabled --restart

	__file /etc/systemd/timesyncd.conf \
		--mode 0644 --onchange "systemctl restart systemd-timesyncd" \
		--source - <<- EOF
		# timesyncd(8) configuration file. Managed by cdist.
		[Time]
		NTP=${peers}
		EOF
	;;
*)
	printf "Unkown backend in __networktime. This is a bug.\n" >&2
	exit 1
	;;
esac
