#!/bin/sh

# Check for installation
cat << EOF
if [ -f '/var/wiki/LICENSE' ];
then
	# Assume everything is done already.
	exit 0;
fi
EOF

# Download and copy source
cat << EOF
wget -O - https://github.com/Requarks/wiki/releases/download/2.4.107/wiki-js.tar.gz | tar xz -C /var/wiki
EOF

# Install deps and launch
cat << EOF
cd /var/wiki || exit 1
npm install
EOF
