#!/bin/sh -e
#
# 2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "${__global:?}/explorer/os")

package=
conffile=
confdir=
case "${os}" in
	"alpine")
		package=bird
		conffile=/etc/bird.conf
		confdir=/etc/bird.d
	;;
	*)
		printf "Your operating system (%s) is currently not supported by __bird_core\n" "${os}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
	;;
esac

router_id=
if [ -f "${__object:?}/parameter/router-id" ];
then
	router_id="router id $(cat "${__object:?}"/parameter/router-id);"
fi

log_params="syslog all"
if [ -f "${__object:?}/parameter/log-params" ];
then
	log_params=$(cat "${__object:?}"/parameter/log-params)
fi

__package "${package}"

export require="__package/${package}"
__directory "${confdir}"
__file "${conffile}" \
	--mode 0640 --owner root --group bird \
	--source - << EOF
# ${conffile} - bird(1) configuration file.
# Managed by cdist. Do not edit by hand.

${router_id}
log ${log_params};

# Always include this "protocol": all it does is expose the available
# interfaces to bird.
protocol device {
	description "Obtain a list of device interfaces.";
}

include "${confdir}/*.conf";
EOF
