#!/bin/sh -e
#
# 2021 Ander Punnar (ander at kvlt.ee)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Prints "present" if --key-path and --cert-path are files, "absent" otherwise.
#

key_path=$(cat "${__object:?}/parameter/key-path")

if echo "${key_path}" | grep -Fq '%s'
then
    # shellcheck disable=SC2059
    key_path=$(printf "${key_path}" "${__object_id:?}")
fi

cert_path=$(cat "${__object:?}/parameter/cert-path")

if echo "${cert_path}" | grep -Fq '%s'
then
    # shellcheck disable=SC2059
    cert_path=$(printf "${cert_path}" "${__object_id:?}")
fi

if [ ! -f "${key_path}" ] || [ ! -f "${cert_path}" ]
then
    echo 'absent'
else
    echo 'present'
fi
