#!/bin/sh -e
#
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

state_should=$(cat "${__object:?}/parameter/state")
os=$(cat "${__global:?}/explorer/os")

if test "${state_should}" != 'absent'
then
	case ${os}
	in
		# (netbsd)
		# 	__package_pkgin subversion-base
		# 	;;
		(openwrt)
			__package_opkg subversion-server
			;;
		(*)
			# default (checked on alpine, archlinux, debian, devuan, fedora,
			# freebsd, openbsd, gentoo, suse, ubuntu)
			__package subversion
			;;
	esac
fi
