#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer looks for lines matching the server parameter in dma's auth.conf
# and reports the login and server fields (password is cksummed)

auth_conf=$("${__type_explorer}/auth_conf")
test -r "${auth_conf}" || exit 0

if test -f "${__object}/parameter/server"
then
	server=$(cat "${__object}/parameter/server")
else
	server=$__object_id
fi

awk -F'\n' -v server="${server}" '
BEGIN {
	DP = "[: \t]"  # copied from dma/conf.c
}

# skip comments and empty lines
/^#/ || /^$/ { next }

{
	login = substr($0, 1, index($0, "|") - 1)
	host = substr($0, length(login) + 2)
	if (match(host, DP)) {
		host = substr(host, 1, RSTART - 1)
		endpos = length(login) + RSTART
	} else endpos = length
}

host == server { print endpos, $0 }
' "${auth_conf}" \
| while read -r pos line
  do
	  printf '%s:%s\n' \
		  "$(printf '%s' "$line" | cut -c $((-pos)))" \
		  "$(printf '%s' "$line" | cut -c $((pos+2))- | cksum | cut -d' ' -f1)"
  done
