#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer lines matching user + server in /etc/dma/auth.conf and reports
# their cksum.

test -r /etc/dma/auth.conf || exit 0

if test -f "${__object}/parameter/login"
then
	login=$(cat "${__object}/parameter/login")
else
	login=$__object_id
fi
server=$(cat "${__object}/parameter/server")

regex=$(printf '^%s|%s:' "$login" "$server")

grep -e "${regex}" /etc/dma/auth.conf \
| while read -r line
  do
	  echo "${line}" \
	  | cksum - \
	  | cut -d ' ' -f 1
  done
