#!/bin/sh
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}"/explorer/os)
init=$(cat "${__global:?}/explorer/init")
nginx_confdir="/etc/nginx"

# The nginx service is not automatically started on alpine.
if [ "${os}" = "alpine" ]; then
	echo "service nginx --ifstopped start"
fi

if grep -qE "^__file${nginx_confdir}" "${__messages_in:?}"; then
	case ${init}
	in
		systemd)
			reload_hook="systemctl reload-or-restart nginx"
			;;
		busybox-init+openrc)
			reload_hook="service nginx reload"
			;;
		*)
			echo "Unknown init ${init}." >&2
			exit 1
			;;
	esac

	cat <<- EOF
	if nginx -t; then
	  ${reload_hook}
	else
	  echo "NGINX configuration is invalid. Exiting." >2&
	  nginx -t >2&
	  exit 1
	fi
	EOF
fi
