#!/bin/sh -e
#
# 2020,2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer returns a sorted list of "active" (= non-commented) lines
# in the dma.conf file.
# "Trailing" line comments are stripped off.
#
# NOTE: This explorer assumes that the sort(1) utility supports the non-POXIX
#       -s (stable sort) option.
#

CONF_PATH=/etc/dma  # set in Makefile
dma_conf="${CONF_PATH:?}/dma.conf"

test -f "${dma_conf}" || exit 0

# NOTE: uses non-POSIX sort(1) stable sort
sed -e 's/[[:blank:]]*#.*$//' -e '/^$/d' "${dma_conf}" \
| sort -s -k 1,1
