#!/bin/sh
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")
init=$(cat "${__global:?}/explorer/init")

case ${os} in
	alpine)
		synapse_conf_dir=/etc/synapse
		synapse_service=synapse
		;;
	debian)
		synapse_conf_dir=/etc/matrix-synapse
		synapse_service=matrix-synapse
		;;
	*)
		echo "Unknown OS ${os}." >&2
		exit 1
	;;
esac

if grep -qE "^__file${synapse_conf_dir}" "${__messages_in:?}"; then
	case ${init} in
		systemd)
			echo "systemctl restart ${synapse_service}"
			;;
		initd)
			echo "service --ifstopped ${synapse_service} start"
			echo "service --ifstarted ${synapse_service} restart"
			;;
		*)
			echo "Unknown init ${init}." >&2
			exit 1
			;;
	esac
fi
