#!/bin/sh
#
# 2015 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Prints "present" if the firewalld rule exists, "absent" otherwise.
#

protocol=$(cat "${__object:?}/parameter/protocol")
table=$(cat "${__object:?}/parameter/table")
chain=$(cat "${__object:?}/parameter/chain")
priority=$(cat "${__object:?}/parameter/priority")
rule=$(cat "${__object:?}/parameter/rule")

if firewall-cmd --permanent --direct --query-rule "${protocol}" "${table}" "${chain}" "${priority}" "${rule}" >/dev/null; then
    echo present
else
    echo absent
fi
