#!/bin/sh -e
#
# 2020-2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

version_ge() { printf '%s\n' "$1" "$2" | sort -t. -r -n | { read -r x; test "${x}" = "$1"; } }

os=$(cat "${__global:?}/explorer/os")
os_version=$(cat "${__global:?}/explorer/os_version")
mach_name=$(cat "${__global:?}/explorer/machine")
init=$(cat "${__global:?}/explorer/init")

case ${os}
in
	(debian|devuan|ubuntu)
		# NOTE: dnsmasq is required for virtual networks (as DHCP, DNS server)
		__package dnsmasq

		# NOTE: ebtables is required for some network filtering options
		__package ebtables

		__update_alternatives iptables --path /usr/sbin/iptables-legacy

		__package qemu-utils

		# NOTE: We have to install netcat-openbsd because libvirt's developers
		# are are complete idiots ignoring the fact that there are different
		# implementations of netcat (like, ones that don't support -U). Moreover
		# they are incapable of printing connection errors on Mac OS X.
		__package netcat-openbsd
		export CDIST_ORDER_DEPENDENCY=true
		__package netcat-traditional --state absent
		__update_alternatives nc --path /bin/nc.openbsd
		unset CDIST_ORDER_DEPENDENCY

		require='__package/dnsmasq __package/ebtables __package/qemu-utils __update_alternatives/nc' \
		__package libvirt-daemon-system
		libvirtd_require=__package/libvirt-daemon-system

		is_bullseye=$(
			case ${os}
			in
				(debian) version_ge "${os_version}" 10.99 ;;
				(devuan) version_ge "${os_version}" 3.99 ;;
				(ubuntu) version_ge "$(os_version)" 20 ;;
				(*) false ;;
			esac && echo true || echo false)

		if ${is_bullseye}
		then
			# should be required by libvirt-daemon-system automaticall,
			# but just to be save…
			if test "${init}" = 'sysvinit'
			then
				__package libvirt-daemon-system-sysv
				libvirtd_require="${libvirtd_require-}${libvirtd_require:+ }__package/libvirt-daemon-system-sysv"
			elif test "${init}" = 'systemd'
			then
				__package libvirt-daemon-system-systemd
				libvirtd_require="${libvirtd_require-}${libvirtd_require:+ }__package/libvirt-daemon-system-systemd"
			fi
		fi

		if test "${init}" != 'systemd'
		then
			require=${libvirtd_require} \
			__key_value /etc/default/libvirtd:mount_cgroups \
				--state present \
				--file /etc/default/libvirtd \
				--delimiter = --exact_delimiter \
				--key 'mount_cgroups' --value 'yes' \
				--onchange '/etc/init.d/libvirtd restart'
		fi

		export require="${require-}${require:+ }${libvirtd_require}"

		__package libvirt-clients

		# cf. https://stackoverflow.com/questions/45125516/possible-values-for-uname-m
		case ${mach_name}
		in
			(aarch64|aarch64_be|armv?l|armv?b)
				__package qemu-system-arm
				qemu_require=__package/qemu-system-arm
				;;
			(ppc64|ppc|ppc64le|ppcle)
				__package qemu-system-ppc
				qemu_require=__package/qemu-system-ppc

				# NOTE: Required to fix this error when creating a new VM in virt-manager:
				# > qemu-system-ppc64le: -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:b8:50:f0,bus=pci.0,addr=0x1: failed to find romfile "efi-virtio.rom"
				#
				# Other than that iPXE doesn’t make any sense on PowerPC,
				# because SLOF can netboot just fine.
				__package ipxe-qemu
				qemu_require="${qemu_require} __package/ipxe-qemu"
				;;
			(mips64|mips)
				__package qemu-system-mips
				qemu_require=__package/qemu-system-mips
				;;
			(sparc64|sparc)
				__package qemu-system-sparc
				qemu_require=__package/qemu-system-sparc
				;;
			(x86_64|i?86)
				__package qemu-kvm
				qemu_require=__package/qemu-kvm
				;;
		esac

		export require="${require-}${require:+ }${qemu_require-}"

		__package_apt libvirt-daemon-driver-storage-zfs \
			--state "$(test -f "${__object:?}/parameter/with-zfs-storage" && echo present || echo absent)"
		;;
	(*)
		: "${__type:?}"  # make shellcheck happy
		printf "Your operating system (%s) is currently not supported by this type (%s)\n" "${os}" "${__type##*/}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac

__key_value /etc/libvirt/libvirtd.conf:unix_sock_group --delimiter ' = ' \
	--key 'unix_sock_group' --value '"libvirt"' \
	--file /etc/libvirt/libvirtd.conf --state present \
	--onchange 'service libvirtd restart'
__key_value /etc/libvirt/libvirtd.conf:unix_sock_rw_perms --delimiter ' = ' \
	--key 'unix_sock_rw_perms' --value '"0770"' \
	--file /etc/libvirt/libvirtd.conf --state present \
	--onchange 'service libvirtd restart'
# TODO: Change SocketMode when using systemd.
__key_value /etc/libvirt/libvirtd.conf:auth_unix_rw --delimiter ' = ' \
	--key 'auth_unix_rw' --value '"none"' \
	--file /etc/libvirt/libvirtd.conf --state present \
	--onchange 'service libvirtd restart'

__key_value /etc/libvirt/libvirtd.conf:audit_logging --delimiter ' = ' \
	--key 'audit_logging' --value '1' \
	--file /etc/libvirt/libvirtd.conf --state present \
	--onchange 'service libvirtd restart'
