#!/bin/sh -e
#
# 2017 Kamila Součková (kamila at ksp.sk)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

version=$(cat "${__object:?}/parameter/version")

kernel_name=$(tr '[:upper:]' '[:lower:]' < "${__global:?}/explorer/kernel_name")
machine=$(cat "${__global:?}/explorer/machine")
case ${machine}
in
	x86_64|amd64)
		arch=amd64
		;;
	x86)
		arch=386
		;;
	*)
		arch=${machine}  # at least try...
		;;
esac

PACKAGE="go${version}.${kernel_name}-${arch}"
URL="https://storage.googleapis.com/golang/${PACKAGE}.tar.gz"
cat <<EOF
[ "x\$(cat /usr/local/go/VERSION 2>/dev/null)" = "xgo${version}" ] && exit 0  # already there
wget --no-verbose "${URL}" -O "/tmp/${PACKAGE}.tar.gz"
rm -rf /usr/local/go
tar -C /usr/local -xzf /tmp/${PACKAGE}.tar.gz
EOF
