#!/bin/sh -e
#
# 2021 pedro (pedro at cas.cat)
# 2021 Evilham (cvs at evilham.com)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

basic_urlencode() {
  echo "${1}" | sed 's/\./%2e/g' | sed 's/-/%2d/g' | sed 's/_/%5f/g'
}

PASSWD=$(cat "${__object:?}/parameter/password" 2>/dev/null || true)
STATE=$(cat "${__object:?}/parameter/state")

if [ -z "${PASSWD}" ] && [ "${STATE}" != "absent" ]; then
  printf "A password is required unless you are removing the user '%s'.\n" >&2 \
    "${__object_id:?}"
fi

JITSI_USER_RAW=${__object_id:?}
if echo "${JITSI_USER_RAW}" | grep -q ".*[A-Z\"&'/:<>@]"; then
  cat >&2 <<EOF
Username (XMPP's localpart) ${JITSI_USER_RAW} has uppercase characters or
contains invalid symbols ("&'/:<>@) according to RFC6122.
EOF
  exit 1
fi

JITSI_USER=$(basic_urlencode "${JITSI_USER_RAW}")
FQDN=$(basic_urlencode "${__target_host:?}")
FQDN_PATH="/var/lib/prosody/${FQDN}/accounts"
FILENAME="${FQDN_PATH}/${JITSI_USER}.dat"

__directory "${FQDN_PATH}" --parents --owner prosody --group prosody --state "present"

require="__directory${FQDN_PATH}" __file "${FILENAME}" --owner prosody --group prosody --mode 0440 \
  --state "${STATE}" --source - <<EOF
return {
	["password"] = "${PASSWD}";
};
EOF
