#!/bin/sh
#
# 2020-2021 Timothée Floure (timothee.floure at posteo.net)
# 2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

if ! [ -f "${__object:?}/parameter/control-use-certs" ];
then
	exit 0;
fi

UNBOUND_CERTS_DIR=/etc/unbound

if [ -f "${__object:?}/parameter/enable-rc" ]
then
	echo "unbound-control-setup -d ${UNBOUND_CERTS_DIR}"
	echo "chown unbound:unbound ${UNBOUND_CERTS_DIR}/*.pem ${UNBOUND_CERTS_DIR}/*.key"
fi

cat << EOF
if pgrep unbound >/dev/null
then
	service ${__object_id:?} reload
else
	service ${__object_id:?} start
fi
EOF
