#!/bin/sh

UNBOUND_CERTS_DIR=/etc/unbound

if [ -f "$__object/parameter/enable_rc" ]; then
	echo "unbound-control-setup -d $UNBOUND_CERTS_DIR"
	echo "chown unbound:unbound $UNBOUND_CERTS_DIR/*.pem $UNBOUND_CERTS_DIR/*.key"
fi
