#!/bin/sh -e
#
# 2017 Kamila Součková (kamila at ksp.sk)
# 2017 Darko Poljak (foss at ungleich.com)
# 2018 Nico Schottelius (nico-cdist at schottelius.org)
# 2018 Dominique Roux (dominique.roux4 at gmail.com)
# 2019 Ahmed Bilal Khalid (ahmedbilal96 at gmail.com)
# 2021 Evilham (cvs at evilham.com)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")
os_version=$(cat "${__global:?}/explorer/os_version")

require=""
case ${os} in
    debian|devuan)
        case ${os_version} in
            8*|jessie)
                # Differntation not needed anymore
                apt_source_distribution=stable
                ;;
            9*|ascii/ceres|ascii)
                # Differntation not needed anymore
                apt_source_distribution=stable
                ;;
            10*|11*)
                # Differntation not needed anymore
                apt_source_distribution=stable
                ;;
            *)
                echo "Don't know how to install Grafana on ${os} ${os_version}. Send us a pull request!" >&2
                exit 1
                ;;
        esac

        __apt_key_uri grafana \
            --name 'Grafana Release Signing Key' \
            --uri https://packages.grafana.com/gpg.key

        require="${require} __apt_key_uri/grafana" __apt_source grafana \
                    --uri https://packages.grafana.com/oss/deb \
                    --distribution ${apt_source_distribution} \
                    --component main
        __package apt-transport-https
        require="${require} __apt_source/grafana" __apt_update_index
        require="${require} __package/apt-transport-https __apt_update_index" __package grafana
        require="${require} __package/grafana" __start_on_boot grafana-server
        require="${require} __start_on_boot/grafana-server" __process grafana-server --start "service grafana-server start"
        ;;
    *)
        echo "Don't know how to install Grafana on ${os}. Send us a pull request!" >&2
        exit 1
        ;;
esac
