#!/bin/sh
#
# 2020-2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

passphrase=
appendonly=

case "$(cat "${__object:?}/parameter/encryption")" in
	none)
		enc=none
		;;
	repokey)
		enc=repokey
		if [ -f "${__object:?}/parameter/passphrase" ];
		then
			passphrase=$(cat "${__object:?}/parameter/passphrase")
		else
			echo "__borg_repo cannot use repokey encryption with no passphrase. Aborting." >&2;
			exit 1;
		fi
		;;
	*)
		echo "$enc is not a known encryption mode for __borg_repo. Aborting." >&2
		exit 1;
esac

if [ -f "${__object:?}/parameter/append-only" ];
then
	appendonly='--append-only'
fi

if [ -f "${__object:?}/parameter/owner" ];
then
	doas="sudo -u '$(cat "${__object:?}/parameter/owner")'"
fi

cat <<- EOF
	set -x
	if [ ! -d "/${__object_id:?}" ]; then
		$doas BORG_NEW_PASSPHRASE=$passphrase borg init -e ${enc:?} $appendonly /${__object_id:?}
	fi
EOF
