#!/bin/sh

os="$(cat "${__global:?}"/explorer/os)"

case "$os" in
	"alpine")
		borg_package=borgbackup
		;;
	*)
		echo "__borg_repo is not yet implemented for os $os. Aborting." >&2;
		exit 1;
esac

__package "$borg_package"

if [ -f "${__object:?}/parameter/owner" ];
then
	__package sudo
fi
