#!/bin/sh -e

os=$(cat "${__global}/explorer/os")

# mailname: default behaviour is different on certain systems
if test -f "${__object}/parameter/mailname"
then
	mailname=$(cat "${__object}/parameter/mailname")
else
	# Otherwise use the hostname
	mailname=$(cat "${__global}/explorer/hostname")
fi

case $os
in
	(debian|devuan|ubuntu)
		# On Debian-like systems use /etc/mailname
		if test -f "${__object}/parameter/mailname"
		then
			echo "$mailname" | __file '/etc/mailname' --state present \
				--mode 0644 --owner root --group root --source -
		fi

		mailname='/etc/mailname'
		;;
esac

# Install DMA
case $os
in
	(debian|devuan|ubuntu)
		__package dma --state present
		export require='__package/dma'
		;;
	(freebsd)
		# Stop sendmail if necessary
		__process 'sendmail' --name 'sendmail.*' --state absent \
			--stop '/etc/rc.d/sendmail onestop'

		# ... and disable it
		__key_value 'rcconf-sendmail-enable' --file '/etc/rc.conf' \
			--key 'sendmail_enable' --delimiter '=' --value '"NONE"' \
			--exact_delimiter

		# Setup mailwrapper accordingly
		__file '/etc/mail/mailer.conf' --mode 0644 --source - <<-'EOF'
			sendmail	/usr/libexec/dma
			send-mail	/usr/libexec/dma
			mailq		/usr/libexec/dma
			newaliases	/usr/libexec/dma
			rmail		/usr/libexec/dma
		EOF
		;;
	(*)
		cat <<EOF >&2
Your OS (${os}) is not supported yet.

Maybe adding support is as simple as adapting the packages or allowing it,
we highly encourage you to open a PR with the necessary changes.
See: https://code.ungleich.ch/ungleich-public/cdist-contrib/
EOF
		exit 1
		;;
esac
