#!/bin/sh -e
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
# 2021 Evilham (cvs at evilham.com)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#


os="$(cat "${__global}/explorer/os")"
if [ "${os}" != "freebsd" ]; then
	exit
fi

# FreeBSD-specific
svdir="/var/service"
svdir_exists="$(cat "${__object}/explorer/svdir-exists")"
runit_etc="$(cat "${__object}/explorer/runit-etc")"

if [ -z "${svdir_exists}" ]; then
	echo "mkdir '${svdir}'"
	sv_restart="YES"
fi
if [ -z "${runit_etc}" ]; then
	echo "cp -R '/usr/local/etc/runit' '/etc/runit'"
	sv_restart="YES"
fi
if grep -q "^__key_value/runsvdir_enable" "${__messages_in}"; then
	sv_restart="YES"
fi

if [ -n "${sv_restart}" ]; then
	echo "service runsvdir restart || service runsvdir start"
fi
