#!/bin/sh -e
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
# 2021 Evilham (cvs at evilham.com)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

__package "runit"

os=$(cat "${__global:?}/explorer/os")
case ${os}
in
	(debian|devuan)
		# zero-config sysvinit and systemd compatibility
		__package runit-run
		;;
	(freebsd)
		__key_value \
			--file "/etc/rc.conf" \
			--key "runsvdir_enable" \
			--delimiter "=" \
			--value "yes" \
			"runsvdir_enable"
		;;
	(*)
		echo "Your OS '${os}' is currently not supported." >&2
		exit 1
		;;
esac
