#!/bin/sh
#
# 2013 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#
# Print the type of the current file/directory at the destination.
#

destination="/${__object_id:?}"

if [ ! -e "${destination}" ]; then
   echo none
elif [ -h "${destination}" ]; then
   echo symlink
elif [ -f "${destination}" ]; then
   echo file
elif [ -d "${destination}" ]; then
   echo directory
else
   echo unknown
fi
