#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer finds the aliases file to modify.

found() { echo "$*"; exit 0; }

check_file() {
	if test -f "$1"
	then
		found "$1"
	fi
}

case $("$__explorer/os")
in
	(freebsd|openbsd|solaris)
		check_file /etc/mail/aliases

		# default
		found /etc/mail/aliases
		;;
	(debian|devuan|ubuntu)
		check_file /etc/aliases

		# default
		found /etc/aliases
		;;
	(*)
		check_file /etc/mail/aliases
		check_file /etc/aliases

		# default
		found /etc/mail/aliases
		;;
esac
