#!/bin/sh

os="$(cat "${__global:?}"/explorer/os)"

case "$os" in
	alpine|ubuntu|debian)
		default_confdir=/etc/ssl/uacme
		;;
	*)
		echo "This type currently has no implementation for $os. Aborting." >&2;
		exit 1
		;;
esac

admin_mail=
if [ -f "${__object:?}/parameter/admin-mail" ];
then
	admin_mail="$(cat "${__object:?}/parameter/admin-mail")";
fi

confdir="${default_confdir:?}"
if [ -f "${__object:?}/parameter/confdir" ];
then
	confdir="$(cat "${__object:?}/parameter/confdir")"
fi

cat << EOF
if ! [ -f "${confdir}/private/key.pem" ];
then
	uacme -y new ${admin_mail}
fi
EOF
