#!/bin/sh
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}"/explorer/os)

case ${os}
in
	alpine|ubuntu|debian)
		default_confdir=/etc/ssl/uacme
		;;
	*)
		echo "This type currently has no implementation for ${os}. Aborting." >&2;
		exit 1
		;;
esac

admin_mail=
if [ -f "${__object:?}/parameter/admin-mail" ];
then
	admin_mail=$(cat "${__object:?}/parameter/admin-mail")
fi

confdir="${default_confdir:?}"
if [ -f "${__object:?}/parameter/confdir" ];
then
	confdir=$(cat "${__object:?}/parameter/confdir")
fi

cat <<EOF
if ! [ -f "${confdir}/private/key.pem" ];
then
	uacme -y new ${admin_mail}
fi
EOF
