#!/bin/sh
#
# 2021 Timothée Floure (timothee.floure at posteo.net)
# 2021 Joachim Desroches (joachim.desroches at epfl.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}"/explorer/os)

case "$os" in
	"alpine"|"debian"|"ubuntu")
		uacme_package=uacme
		;;
	*)
		echo "__uacme_account is not yet implemented for os $os. Aborting." >&2;
		exit 1;
esac

__package $uacme_package
